---
services:
  unifi-db:
    image: mongo:4.4.18
    container_name: unifi-db
    hostname: unifi-db
    env_file: .env
    restart: unless-stopped
    volumes:
      - $BASE_FOLDER/unifi_mongodb:/data
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro
    expose:
      - $MONGO_PORT
    healthcheck:
        test:
          [
            "CMD",
            "mongo",
            "--quiet",
            "127.0.0.1/test",
            "--eval",
            "'quit(db.runCommand({ ping: 1 }).ok ? 0 : 2)'",
          ]
        interval: 10s
        timeout: 10s
        retries: 5
        start_period: 40s

  unifi-network-application:
    image: lscr.io/linuxserver/unifi-network-application:latest
    container_name: unifi-network-application
    env_file: .env
    depends_on: 
      unifi-db:
        condition: service_healthy
    volumes:
      - $BASE_FOLDER/unifi-network-application/data:/config
    ports:
      - 8443:8443
      - 3478:3478/udp
      - 10001:10001/udp
      - 8080:8080
      - 1900:1900/udp #optional
      - 8843:8843 #optional
      - 8880:8880 #optional
      - 6789:6789 #optional
      - 5514:5514/udp #optional
    restart: unless-stopped
